In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.shape

(891, 12)

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [7]:
df[df.Sex=='male'].Survived.value_counts()

0    468
1    109
Name: Survived, dtype: int64

In [8]:
df[['Sex','Survived']].groupby('Sex',as_index=False).mean()

Sex  Survived
0  female  0.742038
1    male  0.188908

In [9]:
df[['SibSp','Survived']].groupby('SibSp',as_index=False).mean()

SibSp  Survived
0      0  0.345395
1      1  0.535885
2      2  0.464286
3      3  0.250000
4      4  0.166667
5      5  0.000000
6      8  0.000000

In [10]:
df[['Pclass','Survived']].groupby('Pclass',as_index=False).mean()

Pclass  Survived
0       1  0.629630
1       2  0.472826
2       3  0.242363

In [11]:
df[['Parch','Survived']].groupby('Parch',as_index=False).mean()

Parch  Survived
0      0  0.343658
1      1  0.550847
2      2  0.500000
3      3  0.600000
4      4  0.000000
5      5  0.200000
6      6  0.000000

In [12]:
df.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [13]:
df.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [14]:
df[df.Embarked=='S'].Survived.value_counts()

0    427
1    217
Name: Survived, dtype: int64

In [15]:
df[df.Embarked=='C'].Survived.value_counts()

1    93
0    75
Name: Survived, dtype: int64

In [16]:
df[df.Embarked=='Q'].Survived.value_counts()

0    47
1    30
Name: Survived, dtype: int64

In [17]:
df[['Embarked','Survived']].groupby('Embarked',as_index=False).mean()

Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.336957

In [18]:
df[(df.Pclass==3)].Survived.value_counts()

0    372
1    119
Name: Survived, dtype: int64

In [19]:
df[(df.Pclass==2)].Survived.value_counts()

0    97
1    87
Name: Survived, dtype: int64

In [20]:
df[(df.Pclass==1)].Survived.value_counts()

1    136
0     80
Name: Survived, dtype: int64

In [21]:
df.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [22]:
df1=df[['Pclass','Sex','Age','Fare','Embarked']]

In [23]:
df1.head()

Pclass     Sex   Age     Fare Embarked
0       3    male  22.0   7.2500        S
1       1  female  38.0  71.2833        C
2       3  female  26.0   7.9250        S
3       1  female  35.0  53.1000        S
4       3    male  35.0   8.0500        S

In [24]:
df1.isnull().sum()

Pclass        0
Sex           0
Age         177
Fare          0
Embarked      2
dtype: int64

In [25]:
df.Age.agg(['max','min','mean','median'])

max       80.000000
min        0.420000
mean      29.699118
median    28.000000
Name: Age, dtype: float64

In [26]:
df1.Age.mean()

29.69911764705882

In [27]:
df1.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [28]:
df1.fillna({'Age':df1.Age.mean(),'Embarked':'S'},inplace=True)

F:\ML\anaconda\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [29]:
df2 = pd.get_dummies(df1[['Sex','Embarked']])
df2.head()

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0           0         1           0           0           1
1           1         0           1           0           0
2           1         0           0           0           1
3           1         0           0           0           1
4           0         1           0           0           1

In [30]:
df3 = df1.select_dtypes(exclude=['object']) 
df3.head()

Pclass   Age     Fare
0       3  22.0   7.2500
1       1  38.0  71.2833
2       3  26.0   7.9250
3       1  35.0  53.1000
4       3  35.0   8.0500

In [31]:
finaldata = pd.concat((df2,df3),axis=1)
finaldata.head()

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  Pclass   Age  \
0           0         1           0           0           1       3  22.0   
1           1         0           1           0           0       1  38.0   
2           1         0           0           0           1       3  26.0   
3           1         0           0           0           1       1  35.0   
4           0         1           0           0           1       3  35.0   

      Fare  
0   7.2500  
1  71.2833  
2   7.9250  
3  53.1000  
4   8.0500

In [32]:
x=finaldata.values
y=df.Survived.values
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[5])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [33]:
from sklearn.feature_selection import SelectKBest,chi2,f_regression
x=SelectKBest(score_func=chi2,k=6).fit_transform(x,y)

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
xtrain,xtest,ytrain,ytest=train_test_split(finaldata.values,df.Survived.values,test_size=.20)

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [37]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)
classifier.fit(xtrain, ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [38]:
classifier.score(xtest,ytest)

0.8659217877094972

In [39]:
pred=classifier.predict(xtest)

In [40]:
from sklearn.metrics import confusion_matrix

In [41]:
confusion_matrix(ytest,pred)

array([[104,  12],
       [ 12,  51]], dtype=int64)

In [42]:
np.unique(ytest)

array([0, 1], dtype=int64)

In [43]:
np.bincount(ytest)

array([116,  63], dtype=int64)